# https://taskfile.dev
# Sous MicroOS, utiliser le script d'installation:
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
# ou installer sous /usr/bin à l'installation de MicroOS

version: '3'

vars: {}

tasks:
  default:
    desc: Liste les tâches.
    cmds:
      - task -l
    silent: true

  certs:ca:
    desc: Crée les autorités de certificats.
    dotenv: ['.env', '{{.ENV}}/.venv']
    cmds:
      - scripts/creer-ca.sh
  certs:manifests:
    desc: Crée les manifestes Kubernetes des secrets de la gestion des certificats.
    dotenv: ['.env', '{{.ENV}}/.venv']
    cmds:
      - scripts/creer-manifeste-secrets-ca.sh
  certs:serveur:
    desc: Crée un certificat 'leaf' pour le serveur
    dotenv: ['.env', '{{.ENV}}/.venv']
    cmds:
      - scripts/ceer-certificat-serveur.sh
  certs:cleanup:
    desc: Supprime les fichiers de certificats générés.
    prompt: Attention! Avez-vous sauvegardé les fichiers de certificats avant de les supprimer?
    cmds:
      - wipe {{.ROOT_DIR}}/certs/*
