# https://taskfile.dev
# Sous MicroOS, utiliser le script d'installation:
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
# ou installer sous /usr/bin à l'installation de MicroOS

version: "3"

env:
  STEPPATH:
    sh: realpath ~/.local/state/step
  CERTS_DIR:
    sh: echo $STEPPATH/certs

vars:
  step:
    map:
      releaseName: acme
      namespace: step-ca
      chartName: step-certificates
  stepConfig:
    map:
      chartPath: paquets/step-ca-secrets
      releaseName: "{{ .step.releaseName }}-config"
      valueOptions: |-
        --namespace {{ .step.namespace }} \
        --set nameOverride={{ .step.chartName }} \
        --set releaseOverride={{ .step.releaseName }} \
        --set-file intermediate_ca.key=$CERTS_DIR/intermediate_ca.key \
        --set-file intermediate_ca.password=$CERTS_DIR/intermediate_ca.password \
        --set-file intermediate_ca.pem=$CERTS_DIR/intermediate_ca.crt \
        --set-file provisioner.key=$CERTS_DIR/jwk_provisioner.encrypted.key \
        --set-file provisioner.password=$CERTS_DIR/jwk_provisioner.password \
        --set-file provisioner.pub=$CERTS_DIR/jwk_provisioner.pub \
        --set-file root_ca.key=$CERTS_DIR/root_ca.key \
        --set-file root_ca.pem=$CERTS_DIR/root_ca.crt \
        --set root_ca.fingerprint=$(step certificate fingerprint $CERTS_DIR/root_ca.crt) \

tasks:
  default:
    desc: Liste les tâches.
    cmds:
      - task -l
    silent: true

  certs:ca:
    desc: Crée les autorités de certificats.
    dotenv: [".env", "{{.ENV}}/.venv"]
    cmds:
      - scripts/creer-ca.sh
  certs:manifests:
    desc: Crée les manifestes Kubernetes des secrets de la gestion des certificats.
    dotenv: [".env", "{{.ENV}}/.venv"]
    cmds:
      - scripts/creer-manifeste-secrets-ca.sh
  certs:serveur:
    desc: Crée un certificat 'leaf' pour le serveur
    dotenv: [".env", "{{.ENV}}/.venv"]
    cmds:
      - scripts/ceer-certificat-serveur.sh
  certs:cleanup:
    desc: Supprime les fichiers de certificats générés.
    prompt: Attention! Avez-vous sauvegardé les fichiers de certificats avant de les supprimer?
    cmds:
      - wipe {{.ROOT_DIR}}/certs/*

  step:config:lint:
    desc: Valide la charte step-ca-secrets de configuration de step-ca
    cmd: |
      helm lint \
      {{ .stepConfig.valueOptions }}
      {{ .stepConfig.chartPath }}
  step:config:render:
    desc: Fait le rendu de la charte step-ca-secrets de configuration de step-ca
    cmd: |
      helm template {{ .stepConfig.releaseName }} \
      {{ .stepConfig.valueOptions }}
      {{ .stepConfig.chartPath }}
  step:config:install:
    desc: Installe les secrets et la configuration prérequis à step-ca (charte step-ca-secrets)
    cmd: |
      kubectl create namespace {{ .step.namespace }} ; \
      helm install {{ .stepConfig.releaseName }} \
      {{ .stepConfig.valueOptions }}
      {{ .stepConfig.chartPath }}
  step:config:upgrade:
    desc: Met à jour les secrets et la configuration prérequises à step-ca (charte step-ca-secrets)
    cmd: |
      helm upgrade {{ .stepConfig.releaseName }} \
      {{ .stepConfig.valueOptions }}
      {{ .stepConfig.chartPath }}
  step:config:uninstall:
    desc: Supprime les secrets et la configuration prérequis à step-ca (charte step-ca-secrets)
    cmd: |
      helm uninstall {{ .stepConfig.releaseName }} ; \
      kubectl delete namespace {{ .step.namespace }}
