#!/bin/bash
# combustion: network
# script generated with https://opensuse.github.io/fuel-ignition/

# Redirect output to the console
exec > >(exec tee -a /dev/tty0) 2>&1

# Keyboard
systemd-firstboot --force --keymap=ca-multix

# Timezone
systemd-firstboot --force --timezone=America/Toronto

# Man pages pas installées; peut-être à générer
zypper --non-interactive install bash-completion bind-utils cockpit-firewalld cockpit-selinux distrobox glibc-locale htop jq kubecolor patterns-microos-cockpit rclone-bash-completion rclone-zsh-completion setools-console starship syncthing tree vim-small yq zsh zsh-htmldoc

# install additional packages for localization
zypper --non-interactive addlocale fr_CA

# download k3s installer
curl -L --output k3s_installer.sh https://get.k3s.io && install -m755 k3s_installer.sh /usr/bin/

# install FetchIt setup script
install -m 755 fetchit-setup.sh /usr/bin/

# Leave a marker
echo "Configured with combustion" > /etc/issue.d/combustion

# Close outputs and wait for tee to finish.
exec 1>&- 2>&-; wait;