# Déploiement CoreDNS comme DNS externe pour réseau local
# Prendre note que ce chart Helm ne supporte qu'une seule zone. On est donc limité à spécifier la zone racine '.:53', et on peut donc inclure des zones supplémentaires avec le plugin 'file'.

serviceType: "LoadBalancer"

# service dns externe
isClusterService: false

service:
  clusterIP: "" # éviter d'interférer avec le réseau interne
  externalTrafficPolicy: Local

# configuration CoreDNS
servers:
  - zones:
      - zone: .
    port: 53
    plugins:
      - name: errors
      - name: health
      - name: ready
      - name: file
        parameters: /etc/coredns/rloc.db rloc
      - name: forward
        # transférer au routeur puis aux serveurs DNS Vidéotron
        parameters: . 24.200.241.37 24.201.245.77
      - name: cache
        parameters: 30

zoneFiles:
  - filename: rloc.db
    domain: rloc
    contents: |
      $ORIGIN rloc.
      $TTL 3600
      @       IN      SOA     ns.rloc. admin.rloc. (
                              2024030901  ; Serial
                              7200        ; Refresh
                              3600        ; Retry
                              1209600     ; Expire
                              3600 )      ; Negative Cache TTL

      @           IN      NS      ns.rloc.
      ns          IN      A       192.168.50.247 ; cluster k3s

      arcade      IN      A       192.168.50.185
      ai          IN      CNAME   arcade.rloc.
      ia          IN      CNAME   arcade.rloc.

      motel       IN      A       192.168.50.247
      cloud       IN      CNAME   motel.rloc.
      kubernetes  IN      CNAME   motel.rloc.
      nuage       IN      CNAME   motel.rloc.

      routeur     IN      A       192.168.50.1
