# configuration d'un agent, un worker k3s
server: https://kubernetes.rloc:6443
token-file: /etc/rancher/k3s/node-token
default-runtime: nvidia
node-label:
  - gpu=nvidia
  - node-role.kubernetes.io/gpu=true
  - node-role.kubernetes.io/worker=true
# appliquer le taint après la configuration de l'agent et le déploiement
# du NVIDIA device plugin, et de Node Feature Discovery
# node-taint:
#   - nvidia.com/gpu:NoSchedule
