apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: app1
      name: app1
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: app1
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: app1
        spec:
          containers:
            - image: nginx
              imagePullPolicy: Always
              name: nginx
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: app1
      name: app1
      namespace: default
    spec:
      ports:
        - port: 80
      selector:
        app: app1
kind: List
