apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: app2
      name: app2
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: app2
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: app2
        spec:
          containers:
            - image: httpd
              imagePullPolicy: Always
              name: httpd
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: app2
      name: app2
      namespace: default
    spec:
      ports:
        - port: 80
      selector:
        app: app2
kind: List
