# Secrets requis par step-ca et le chart step-certificates
apiVersion: v1
kind: Secret
type: smallstep.com/ca-password
metadata:
  annotations:
    kubernetes.io/description: Mot de passe du certificat émetteur (intermediate_ca)
  name: {{ include "step-ca-secrets.fullname" . }}-ca-password
  namespace: {{ .Release.Namespace }}
data:
  password: {{ required "secrets.intermediate_ca_password est requise" .Values.secrets.intermediate_ca_password | b64enc }}
---
apiVersion: v1
kind: Secret
type: smallstep.com/provisioner-password
metadata:
  annotations:
    kubernetes.io/description: Mot de passe du certificat du provisionneur JWK
  name: {{ include "step-ca-secrets.fullname" . }}-provisioner-password
  namespace: {{ .Release.Namespace }}
data:
  password: {{ required "secrets.provisioner_password est requise" .Values.secrets.provisioner_password | b64enc }}
---
apiVersion: v1
kind: Secret
type: smallstep.com/private-keys
metadata:
  annotations:
    kubernetes.io/description: Clés chiffrées des autorités de certificat intermédiaire (émetteur) et racine
  name: {{ include "step-ca-secrets.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  intermediate_ca_key: |-{{ required "secrets.intermediate_ca_key est requise" .Values.secrets.intermediate_ca_key | nindent 4 }}
  root_ca_key: |-{{ required "secrets.root_ca_key est requise" .Values.secrets.root_ca_key | nindent 4 }}
