configReload:
  configURL: https://raw.githubusercontent.com/SylChamber/labo-perso/main/systeme/services/config.yaml
  schedule: "*/3 * * * *"
# Déploiement via GitOps de conteneurs Podman avec FetchIt
targetConfigs:
# Déploiement de CoreDNS
- url: https://github.com/SylChamber/labo-perso
  branch: main
  kube:
  - name: coredns
    targetPath: systeme/services/dns
    schedule: "*/3 * * * *"
